# Generated by Django 3.2.8 on 2022-11-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20221101_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=200)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.category')),
            ],
        ),
        migrations.AddField(
            model_name='mdata',
            name='category',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.category'),
        ),
        migrations.AddField(
            model_name='mdata',
            name='subcategory',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.subcategory'),
        ),
    ]
