# Generated by Django 3.2.8 on 2022-11-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_subcategory_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.category'),
        ),
        migrations.AlterField(
            model_name='mdata',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.subcategory'),
        ),
    ]
