# Generated by Django 3.2.8 on 2022-11-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20221101_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='mdata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mdata',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
