# Generated by Django 3.2.8 on 2022-11-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20221107_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='brand',
        ),
    ]
