# Generated by Django 3.2.8 on 2022-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_type_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdata',
            name='rateing',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
