# Generated by Django 3.2.8 on 2022-11-14 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_mdata_rateing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdata',
            name='rateing',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
